### ISSUE TITLE
Docset doesn't work in Zeal

### ISSUE THREAD

**Issue by jlbruno** [clavery/docset-sfcc-b2c#1]
I downloaded the latest docset from the Release tab and manually installed in Zeal by putting the docset in the `AppData\Local\Zeal\Zeal\docsets` folder. It shows up appropriately when opening Zeal, but when clicking on anything in the navigation, I receive an error page saying that the system can't find the file specified. 

![image](https://user-images.githubusercontent.com/240571/231580554-7e11dcbf-6c8a-484e-8c26-560c6623096e.png)

Using Zeal version 0.6.1 on Windows 10.

**Comment by jlbruno** [comment]
I did just realize that some of the sections work properly, while others return the error in my original post. 

Builtins, Classes, Procedures are all broken.
Guides, Protocols, Resources, Tags, Types are all working. 

![image](https://user-images.githubusercontent.com/240571/232545812-1d828770-00fe-4651-b2e0-4aa6b3e51ed2.png)

**Comment by clavery** [comment]
This should be fixed in the latest version.

Also can use this feed url instead of manual install: https://raw.githubusercontent.com/clavery/docset-sfcc-b2c/main/SFCC_API.xml
